name: WB Stock Days Report

on:
  schedule:
    - cron: "0 7 * * 1,5"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install deps
        run: |
          pip install pandas boto3 openpyxl xlsxwriter requests

      - name: Run script
        env:
          YC_ACCESS_KEY_ID: ${{ secrets.YC_ACCESS_KEY_ID }}
          YC_SECRET_ACCESS_KEY: ${{ secrets.YC_SECRET_ACCESS_KEY }}
          YC_BUCKET_NAME: ${{ secrets.YC_BUCKET_NAME }}

          CLOUD_RU_ACCESS_KEY: ${{ secrets.CLOUD_RU_ACCESS_KEY }}
          CLOUD_RU_SECRET_KEY: ${{ secrets.CLOUD_RU_SECRET_KEY }}
          CLOUD_RU_BUCKET: ${{ secrets.CLOUD_RU_BUCKET }}

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          URL_1C_STOCKS: ${{ secrets.URL_1C_STOCKS }}

        run: python wb_stock_days_report.py
